/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoi;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lemaun
 */
public class JFProjetoI extends javax.swing.JFrame {

    /**
     * Creates new form JFProjetoI
     */
    public JFProjetoI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        diasTrabalhadosText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        horasTrabalhadasText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        resultadoDisponibilidadeText = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        rCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        mensagemProducaoText = new javax.swing.JLabel();
        resultadoCarregamentoText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        produtoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        taxaProducaoText = new javax.swing.JTextField();
        setupText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        previsaoText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        horasExtraText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        horasExtraDiaText = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Produção");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Frutiger-Black", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoi/logo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getSize()+1f));
        jLabel11.setText("Dias Trabalhados:");

        diasTrabalhadosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasTrabalhadosTextActionPerformed(evt);
            }
        });

        jLabel12.setFont(jLabel12.getFont().deriveFont(jLabel12.getFont().getSize()+1f));
        jLabel12.setText("Horas Trabalhadas:");

        horasTrabalhadasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasTrabalhadasTextActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("DISPONIBILIDADE");

        resultadoDisponibilidadeText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        resultadoDisponibilidadeText.setForeground(new java.awt.Color(204, 0, 51));
        resultadoDisponibilidadeText.setText("0");

        jLabel13.setFont(jLabel13.getFont().deriveFont(jLabel13.getFont().getSize()+1f));
        jLabel13.setText("Mes:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(diasTrabalhadosText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addComponent(horasTrabalhadasText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultadoDisponibilidadeText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(diasTrabalhadosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(horasTrabalhadasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resultadoDisponibilidadeText)
                        .addComponent(jLabel8)
                        .addComponent(jButton2))
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabela.setAutoCreateRowSorter(true);
        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Produto", "Taxa de Produção", "Setup", "Previsão", "Carregamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTabela);
        jTabela.getColumnModel().getColumn(0).setMinWidth(60);
        jTabela.getColumnModel().getColumn(0).setMaxWidth(60);
        jTabela.getColumnModel().getColumn(1).setMinWidth(240);
        jTabela.getColumnModel().getColumn(1).setMaxWidth(240);
        jTabela.getColumnModel().getColumn(2).setMinWidth(150);
        jTabela.getColumnModel().getColumn(2).setMaxWidth(150);
        jTabela.getColumnModel().getColumn(3).setMinWidth(100);
        jTabela.getColumnModel().getColumn(3).setMaxWidth(100);
        jTabela.getColumnModel().getColumn(4).setMinWidth(100);
        jTabela.getColumnModel().getColumn(4).setMaxWidth(100);
        jTabela.getColumnModel().getColumn(5).setMinWidth(100);
        jTabela.getColumnModel().getColumn(5).setMaxWidth(100);

        mensagemProducaoText.setBackground(new java.awt.Color(0, 0, 0));
        mensagemProducaoText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        mensagemProducaoText.setForeground(new java.awt.Color(153, 153, 153));
        mensagemProducaoText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resultadoCarregamentoText.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        resultadoCarregamentoText.setForeground(new java.awt.Color(204, 0, 51));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setText("CARREGAMENTO TOTAL");

        jPanel3.setBackground(new java.awt.Color(228, 228, 228));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+1f));
        jLabel2.setText("Código");

        codigoText.setText("1");
        codigoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextActionPerformed(evt);
            }
        });

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+1f));
        jLabel3.setText("Nome do Produto");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()+1f));
        jLabel4.setText("Taxa de Produção (hora)");

        taxaProducaoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaProducaoTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()+1f));
        jLabel5.setText("Setup (horas)");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+1f));
        jLabel6.setText("Previsão Mês");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoi/add.png"))); // NOI18N
        jButton1.setText("  Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        previsaoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previsaoTextActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoi/Delete.png"))); // NOI18N
        jButton3.setText("  Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("CADASTRO DE PRODUTOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel6)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(taxaProducaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addGap(4, 4, 4)
                                    .addComponent(setupText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(produtoText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(previsaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(produtoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxaProducaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(setupText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6))
                    .addComponent(previsaoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        horasExtraText.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        horasExtraText.setForeground(new java.awt.Color(204, 0, 51));
        horasExtraText.setText("0");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("HORAS EXTRAS NECESSÁRIAS");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("MES");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("DIA");

        horasExtraDiaText.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        horasExtraDiaText.setForeground(new java.awt.Color(204, 0, 51));
        horasExtraDiaText.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horasExtraText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horasExtraDiaText, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultadoCarregamentoText, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mensagemProducaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rCodigo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resultadoCarregamentoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(horasExtraText)
                            .addComponent(jLabel15)
                            .addComponent(horasExtraDiaText)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensagemProducaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Reiniciar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu2);

        jMenu1.setText("Sobre");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-793)/2, (screenSize.height-652)/2, 793, 652);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (horasTrabalhadasText.getText().isEmpty()
                || diasTrabalhadosText.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Obrigatório o preenchimento de todos os campos.", "Atenção", JOptionPane.WARNING_MESSAGE);

        }

        int dias = Integer.parseInt(diasTrabalhadosText.getText());
        double horas = Double.parseDouble(horasTrabalhadasText.getText());

        //calculo disponibilidade
        double resultadoDisponilidade = dias * horas;

        //chamando classe DecimalFomart e configurando com 2 digitos as casa decimais
        DecimalFormat myformat = new DecimalFormat();
        myformat.setMaximumFractionDigits(2);
        myformat.setMinimumFractionDigits(2);

        resultadoDisponibilidadeText.setText(String.valueOf(resultadoDisponilidade));

        //so calcula disponibilidade ser conter algum conteudo no carregamento total
        if (!(resultadoCarregamentoText.getText()).isEmpty()) {

            //soma total carregamento
            int qtdeLinhas = jTabela.getRowCount();
            Double soma = 0.0;
            for (int i = 0; i < qtdeLinhas; i++) {
                soma += (Double) jTabela.getValueAt(i, 5);
            }

            String somaNova = myformat.format(soma);
            resultadoCarregamentoText.setText(somaNova);
            double resultadoTotal = soma;

            //verificar disponibilidade
            double horasExtrasResult = Math.abs(resultadoDisponilidade - resultadoTotal);
            double horasExtrasResultDias = horasExtrasResult / dias;

            //formataçao casa decimais
            String horasExtrasFormat = myformat.format(horasExtrasResult);
            String horasExtrasDiasFormat = myformat.format(horasExtrasResultDias);

            //icons
            ImageIcon iconAutorizado = new ImageIcon(getClass().getResource("autorizado.png"));
            ImageIcon iconNaoAutorizado = new ImageIcon(getClass().getResource("naoautorizado.png"));

            //disponibilidade
            if (resultadoTotal <= resultadoDisponilidade) {
                mensagemProducaoText.setIcon(iconAutorizado);
                horasExtraText.setText("0");
                horasExtraDiaText.setText("0");
            } else {
                mensagemProducaoText.setIcon(iconNaoAutorizado);
                JOptionPane.showMessageDialog(null, "Carregamento não suportado. \nSão necessárias: " + horasExtrasFormat + " horas extras.", "Atenção", JOptionPane.WARNING_MESSAGE);
                horasExtraText.setText(horasExtrasFormat);
                horasExtraDiaText.setText(horasExtrasDiasFormat);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void horasTrabalhadasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasTrabalhadasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasTrabalhadasTextActionPerformed

    private void diasTrabalhadosTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasTrabalhadosTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasTrabalhadosTextActionPerformed

    private void previsaoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previsaoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previsaoTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //verificação dos campos
        if (codigoText.getText().isEmpty()
                || produtoText.getText().isEmpty()
                || taxaProducaoText.getText().isEmpty()
                || setupText.getText().isEmpty()
                || previsaoText.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Obrigatório o preenchimento de todos os campos.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }

        //captura dados
        Produtos produtos = new Produtos();
        produtos.setCodigo(Integer.parseInt(codigoText.getText()));
        produtos.setNome(produtoText.getText());
        produtos.setTaxa(Double.parseDouble(taxaProducaoText.getText()));
        produtos.setSetup(Double.parseDouble(setupText.getText()));
        produtos.setPrevisao(Double.parseDouble(previsaoText.getText()));
        produtos.carregamento();

        //tabela
        DefaultTableModel model = (DefaultTableModel) jTabela.getModel();

        //criação vetor
        Object[] vetor = new Object[6];
        vetor[0] = produtos.getCodigo();
        vetor[1] = produtos.getNome();
        vetor[2] = produtos.getTaxa();
        vetor[3] = produtos.getSetup();
        vetor[4] = produtos.getPrevisao();
        vetor[5] = produtos.carregamento();

        //inserçao na tabela
        model.addRow(vetor);

        //soma total carregamento
        int qtdeLinhas = jTabela.getRowCount();
        Double soma = 0.0;
        for (int i = 0; i < qtdeLinhas; i++) {
            soma += (Double) jTabela.getValueAt(i, 5);
        }

        //formataçao decimais
        DecimalFormat myformat = new DecimalFormat();
        myformat.setMaximumFractionDigits(2);
        myformat.setMinimumFractionDigits(2);
        String somaNova = myformat.format(soma);
        resultadoCarregamentoText.setText(somaNova);

        //autonumera o código
        int numeradorAux = produtos.getCodigo() + 1;
        String numerador = String.valueOf(numeradorAux);

        //verificar disponibilidade
        double resultadoTotal = soma;
        double resultadoDisp = Double.parseDouble(resultadoDisponibilidadeText.getText());

        //captura dias trabalhados
        if (!(diasTrabalhadosText.getText()).isEmpty()) {
            int dias = Integer.parseInt(diasTrabalhadosText.getText());

            //calculos
            double horasExtrasResult = Math.abs(resultadoDisp - resultadoTotal);
            double horasExtrasResultDias = horasExtrasResult / dias;

            //formataçao casa decimais
            String horasExtrasFormat = myformat.format(horasExtrasResult);
            String horasExtrasDiasFormat = myformat.format(horasExtrasResultDias);

            //icons
            ImageIcon iconAutorizado = new ImageIcon(getClass().getResource("autorizado.png"));
            ImageIcon iconNaoAutorizado = new ImageIcon(getClass().getResource("naoautorizado.png"));

            if (resultadoTotal <= resultadoDisp) {
                mensagemProducaoText.setIcon(iconAutorizado);
                horasExtraText.setText("0");
                horasExtraDiaText.setText("0");
            } else {
                mensagemProducaoText.setIcon(iconNaoAutorizado);
                JOptionPane.showMessageDialog(null, "Carregamento não suportado. \nSão necessárias: " + horasExtrasFormat + " horas extras.", "Atenção", JOptionPane.WARNING_MESSAGE);
                horasExtraText.setText(horasExtrasFormat);
                horasExtraDiaText.setText(horasExtrasDiasFormat);
            }
        }

        //limpando campos
        codigoText.setText(numerador);
        produtoText.setText("");
        taxaProducaoText.setText("");
        setupText.setText("");
        previsaoText.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void taxaProducaoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaProducaoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaProducaoTextActionPerformed

    private void codigoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel remover = (DefaultTableModel) jTabela.getModel();
        if (jTabela.getSelectedRow() >= 0) {
            remover.removeRow(jTabela.getSelectedRow());
            jTabela.setModel(remover);
        }

        //soma total carregamento
        int qtdeLinhas = jTabela.getRowCount();
        Double soma = 0.0;
        for (int i = 0; i < qtdeLinhas; i++) {
            soma += (Double) jTabela.getValueAt(i, 5);
        }

        DecimalFormat myformat = new DecimalFormat();
        myformat.setMaximumFractionDigits(2);
        myformat.setMinimumFractionDigits(2);
        String somaNova = myformat.format(soma);
        resultadoCarregamentoText.setText(somaNova);

        //verificar disponibilidade
        double resultadoTotal = soma;
        double resultadoDisp = Double.parseDouble(resultadoDisponibilidadeText.getText());

        //captura dias trabalhados
        int dias = Integer.parseInt(diasTrabalhadosText.getText());

        //calculos
        double horasExtrasResult = Math.abs(resultadoDisp - resultadoTotal);
        double horasExtrasResultDias = horasExtrasResult / dias;

        //formataçao casa decimais
        String horasExtrasFormat = myformat.format(horasExtrasResult);
        String horasExtrasDiasFormat = myformat.format(horasExtrasResultDias);

        //icon
        ImageIcon iconAutorizado = new ImageIcon(getClass().getResource("autorizado.png"));
        ImageIcon iconNaoAutorizado = new ImageIcon(getClass().getResource("naoautorizado.png"));

        if (resultadoTotal <= resultadoDisp) {
            mensagemProducaoText.setIcon(iconAutorizado);
            horasExtraText.setText("0");
            horasExtraDiaText.setText("0");
        } else {
            mensagemProducaoText.setIcon(iconNaoAutorizado);
            JOptionPane.showMessageDialog(null, "Carregamento não suportado. \nSão necessárias: " + horasExtrasFormat + " horas extras.", "Atenção", JOptionPane.WARNING_MESSAGE);
            horasExtraText.setText(horasExtrasFormat);
            horasExtraDiaText.setText(horasExtrasDiasFormat);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked

        int res;
        res = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema?", "Sair....", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        JFSobre sobre = new JFSobre();
        sobre.show();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String resposta = (String) jComboBox1.getSelectedItem();
        diasUteisEHoras diasHorasUteis = new diasUteisEHoras();

        String respostaMes = diasHorasUteis.itemSelecionado(resposta);
        
        if (respostaMes != null) {
            diasTrabalhadosText.setText(respostaMes);
            horasTrabalhadasText.setText(diasHorasUteis.horas);

            double resultadoDisponilidade = (Integer.parseInt(diasHorasUteis.horas)) * (Integer.parseInt(respostaMes));
            resultadoDisponibilidadeText.setText(String.valueOf(resultadoDisponilidade));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        int resposta;
        resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja resetar o sistema? "
                + "\nVocê ira perder todos os dados!", "Reiniciar Sistema", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {

            //limpando campos
            codigoText.setText("1");
            produtoText.setText("");
            taxaProducaoText.setText("");
            setupText.setText("");
            previsaoText.setText("");
            resultadoCarregamentoText.setText("0");
            resultadoDisponibilidadeText.setText("0");
            jComboBox1.setSelectedIndex(0);
            diasTrabalhadosText.setText("");
            horasTrabalhadasText.setText("");
            mensagemProducaoText.setIcon(null);
            horasExtraText.setText("");
            horasExtraDiaText.setText("");

            //limpando tabela
            DefaultTableModel remover = (DefaultTableModel) jTabela.getModel();
            if (jTabela.getRowCount() >= 0) {
                int numeroLinhas = jTabela.getRowCount();
                for (int i = numeroLinhas; i > 0; i--) {
                    remover.removeRow(0);
                }
            }
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProjetoI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProjetoI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProjetoI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProjetoI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProjetoI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoText;
    private javax.swing.JTextField diasTrabalhadosText;
    private javax.swing.JLabel horasExtraDiaText;
    private javax.swing.JLabel horasExtraText;
    private javax.swing.JTextField horasTrabalhadasText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JLabel mensagemProducaoText;
    private javax.swing.JTextField previsaoText;
    private javax.swing.JTextField produtoText;
    private javax.swing.JLabel rCodigo;
    private javax.swing.JLabel resultadoCarregamentoText;
    private javax.swing.JLabel resultadoDisponibilidadeText;
    private javax.swing.JTextField setupText;
    private javax.swing.JTextField taxaProducaoText;
    // End of variables declaration//GEN-END:variables
}